In [41]:
import numpy as np

In [42]:
npz_data = np.load("./MyWebcamCalibData.npz")

In [43]:
npz_data.files

['mtx', 'dist', 'rvecs', 'tvecs']

In [44]:
a = np.float32(npz_data["mtx"])
print(type(a))
print("data type of a ={}".format(a.dtype))
print(a)

<class 'numpy.ndarray'>
data type of a =float32
[[569.3313    0.      326.86475]
 [  0.      567.715   238.67073]
 [  0.        0.        1.     ]]


In [45]:
import yaml
with open("./MyCameraConfig.yml") as f:
    data = yaml.load(f, Loader=yaml.FullLoader)
    print(data['camera_matrix']['data'])

[716.2257605610685, 0.0, 809.340956752432, 0.0, 716.2257605610685, 384.43357542338293, 0.0, 0.0, 1.0]


### Code explanation related to np package

In [46]:
## Object point creation step
import numpy as np
objp = np.zeros((9 * 7, 3), np.float32)
print("shape:{}".format(objp.shape))
print(objp)

shape:(63, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Look the image below to see the np.mgrid explanation. _The dimensions and number of the output arrays are equal to the number of indexing dimensions_. If the step length is not a complex number, then the stop is not inclusive.

![np.mgrid](./DocsExplanation/numpy-mgrid-function-image-1.png)

In [47]:
np.mgrid[0:4, 0:4]

array([[[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [48]:
a = np.mgrid[1:11:2, -12:-3:3]
print("shape:{}".format(a.shape))
print("a = \n{}".format(a))

shape:(2, 5, 3)
a = 
[[[  1   1   1]
  [  3   3   3]
  [  5   5   5]
  [  7   7   7]
  [  9   9   9]]

 [[-12  -9  -6]
  [-12  -9  -6]
  [-12  -9  -6]
  [-12  -9  -6]
  [-12  -9  -6]]]


In [49]:
x1, y1 = np.mgrid[1:11:2, -12:-3:3]
print("x1 shape = {}".format(x1.shape))
print("x1  data is: \n {}".format(x1))
print("------------------")
print("y1 shape = {}".format(y1.shape))
print("y1  data is: \n {}".format(y1))

x1 shape = (5, 3)
x1  data is: 
 [[1 1 1]
 [3 3 3]
 [5 5 5]
 [7 7 7]
 [9 9 9]]
------------------
y1 shape = (5, 3)
y1  data is: 
 [[-12  -9  -6]
 [-12  -9  -6]
 [-12  -9  -6]
 [-12  -9  -6]
 [-12  -9  -6]]


In [50]:
a = np.mgrid[0:9, 0:7]
print("Shape: {}".format(a.shape))
print("a = \n{}".format(a))

Shape: (2, 9, 7)
a = 
[[[0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1]
  [2 2 2 2 2 2 2]
  [3 3 3 3 3 3 3]
  [4 4 4 4 4 4 4]
  [5 5 5 5 5 5 5]
  [6 6 6 6 6 6 6]
  [7 7 7 7 7 7 7]
  [8 8 8 8 8 8 8]]

 [[0 1 2 3 4 5 6]
  [0 1 2 3 4 5 6]
  [0 1 2 3 4 5 6]
  [0 1 2 3 4 5 6]
  [0 1 2 3 4 5 6]
  [0 1 2 3 4 5 6]
  [0 1 2 3 4 5 6]
  [0 1 2 3 4 5 6]
  [0 1 2 3 4 5 6]]]


In [51]:
b = np.mgrid[0:9, 0:7].T
print("Shape: {}".format(b.shape))
print("b = \n{}".format(b))

Shape: (7, 9, 2)
b = 
[[[0 0]
  [1 0]
  [2 0]
  [3 0]
  [4 0]
  [5 0]
  [6 0]
  [7 0]
  [8 0]]

 [[0 1]
  [1 1]
  [2 1]
  [3 1]
  [4 1]
  [5 1]
  [6 1]
  [7 1]
  [8 1]]

 [[0 2]
  [1 2]
  [2 2]
  [3 2]
  [4 2]
  [5 2]
  [6 2]
  [7 2]
  [8 2]]

 [[0 3]
  [1 3]
  [2 3]
  [3 3]
  [4 3]
  [5 3]
  [6 3]
  [7 3]
  [8 3]]

 [[0 4]
  [1 4]
  [2 4]
  [3 4]
  [4 4]
  [5 4]
  [6 4]
  [7 4]
  [8 4]]

 [[0 5]
  [1 5]
  [2 5]
  [3 5]
  [4 5]
  [5 5]
  [6 5]
  [7 5]
  [8 5]]

 [[0 6]
  [1 6]
  [2 6]
  [3 6]
  [4 6]
  [5 6]
  [6 6]
  [7 6]
  [8 6]]]


In [52]:
np.mgrid[0:9, 0:7].T.reshape(-1, 2)

array([[0, 0],
       [1, 0],
       [2, 0],
       [3, 0],
       [4, 0],
       [5, 0],
       [6, 0],
       [7, 0],
       [8, 0],
       [0, 1],
       [1, 1],
       [2, 1],
       [3, 1],
       [4, 1],
       [5, 1],
       [6, 1],
       [7, 1],
       [8, 1],
       [0, 2],
       [1, 2],
       [2, 2],
       [3, 2],
       [4, 2],
       [5, 2],
       [6, 2],
       [7, 2],
       [8, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [3, 3],
       [4, 3],
       [5, 3],
       [6, 3],
       [7, 3],
       [8, 3],
       [0, 4],
       [1, 4],
       [2, 4],
       [3, 4],
       [4, 4],
       [5, 4],
       [6, 4],
       [7, 4],
       [8, 4],
       [0, 5],
       [1, 5],
       [2, 5],
       [3, 5],
       [4, 5],
       [5, 5],
       [6, 5],
       [7, 5],
       [8, 5],
       [0, 6],
       [1, 6],
       [2, 6],
       [3, 6],
       [4, 6],
       [5, 6],
       [6, 6],
       [7, 6],
       [8, 6]])

In [53]:
objp[:, :2] = np.mgrid[0:9, 0:7].T.reshape(-1, 2)

In [54]:
print("Objp shape={}".format(objp.shape))
print("Objp after resize =\n {}".format(objp))

Objp shape=(63, 3)
Objp after resize =
 [[0. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]
 [5. 0. 0.]
 [6. 0. 0.]
 [7. 0. 0.]
 [8. 0. 0.]
 [0. 1. 0.]
 [1. 1. 0.]
 [2. 1. 0.]
 [3. 1. 0.]
 [4. 1. 0.]
 [5. 1. 0.]
 [6. 1. 0.]
 [7. 1. 0.]
 [8. 1. 0.]
 [0. 2. 0.]
 [1. 2. 0.]
 [2. 2. 0.]
 [3. 2. 0.]
 [4. 2. 0.]
 [5. 2. 0.]
 [6. 2. 0.]
 [7. 2. 0.]
 [8. 2. 0.]
 [0. 3. 0.]
 [1. 3. 0.]
 [2. 3. 0.]
 [3. 3. 0.]
 [4. 3. 0.]
 [5. 3. 0.]
 [6. 3. 0.]
 [7. 3. 0.]
 [8. 3. 0.]
 [0. 4. 0.]
 [1. 4. 0.]
 [2. 4. 0.]
 [3. 4. 0.]
 [4. 4. 0.]
 [5. 4. 0.]
 [6. 4. 0.]
 [7. 4. 0.]
 [8. 4. 0.]
 [0. 5. 0.]
 [1. 5. 0.]
 [2. 5. 0.]
 [3. 5. 0.]
 [4. 5. 0.]
 [5. 5. 0.]
 [6. 5. 0.]
 [7. 5. 0.]
 [8. 5. 0.]
 [0. 6. 0.]
 [1. 6. 0.]
 [2. 6. 0.]
 [3. 6. 0.]
 [4. 6. 0.]
 [5. 6. 0.]
 [6. 6. 0.]
 [7. 6. 0.]
 [8. 6. 0.]]


### Image test

In [55]:
import cv2
# Term Criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
objpoints = []  # 3d point in the real world space
imgpoints = []  # 2d point in the image plane
img = cv2.imread("./dataLogiWebcam/calib_img0.jpg")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Find the chess board corners
ret, corners = cv2.findChessboardCorners(gray, (9, 7), None)
objpoints.append(objp)
cv2.cornerSubPix(gray, corners, (5, 5), (-1, -1), criteria)
imgpoints.append(corners)

In [56]:
print("objpoints shape={}\n".format(np.array(objpoints).shape))
print("imgpoints shape={}\n".format(np.array(imgpoints).shape))

objpoints shape=(1, 63, 3)

imgpoints shape=(1, 63, 1, 2)



In [57]:
# Calibration
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(
    objpoints, imgpoints, gray.shape[::-1], None, None)

In [58]:
npz_data = np.load("./MyWebcamCalibData.npz")

In [59]:
npz_data.files

['mtx', 'dist', 'rvecs', 'tvecs']

In [60]:
for i in npz_data.files:
    print("{}\n\t{}".format(i,npz_data[i]))

mtx
	[[569.33130534   0.         326.86474954]
 [  0.         567.71501546 238.67073028]
 [  0.           0.           1.        ]]
dist
	[[-5.06604551e-02  9.12567910e-01 -3.86302767e-04 -2.80605520e-04
  -2.70111897e+00]]
rvecs
	[[[-0.08342793]
  [ 0.21233694]
  [ 0.66736743]]

 [[ 0.61947451]
  [ 0.09555203]
  [ 2.97933884]]

 [[-0.21751133]
  [ 0.29756352]
  [ 3.07020654]]

 [[ 0.06791767]
  [ 0.11236676]
  [ 3.08499725]]

 [[-0.24003147]
  [-0.71905251]
  [-0.06000225]]

 [[ 0.14394083]
  [ 0.24275739]
  [ 2.63579615]]

 [[-0.08192002]
  [ 0.17888293]
  [ 3.05737778]]

 [[ 0.23985707]
  [ 0.30791281]
  [ 1.55340107]]

 [[-0.11189545]
  [ 0.17001606]
  [ 1.84109176]]]
tvecs
	[[[-4.71381111]
  [-4.39357755]
  [21.94763556]]

 [[ 2.67770409]
  [ 1.55031159]
  [18.09568139]]

 [[ 2.89412622]
  [ 2.09624724]
  [19.06185863]]

 [[ 1.83791554]
  [ 3.63321059]
  [18.3164755 ]]

 [[-6.88108504]
  [-2.70754815]
  [16.38343767]]

 [[ 1.80187791]
  [ 0.73229979]
  [18.48862616]]

 [[ 5.260017

## Use of _cv2.Rodrigues()_

In [61]:
rvec = np.array([[-0.03067108],
 [ 0.69098701],
 [ 2.99420159]])

In [62]:
rvec

array([[-0.03067108],
       [ 0.69098701],
       [ 2.99420159]])

In [63]:
rvec.shape

(3, 1)

In [64]:
rvec.dtype

dtype('float64')

In [65]:
rotation_matrix = cv2.Rodrigues(np.float32(rvecs))[0]

In [66]:
rotation_matrix

array([[ 0.99167675, -0.10235471,  0.07810739],
       [ 0.07656959,  0.95654786,  0.28134197],
       [-0.10351013, -0.27301964,  0.9564235 ]], dtype=float32)

In [67]:
rotation_matrix1, jacob = cv2.Rodrigues(np.float32(rvecs))
print(rotation_matrix1.shape)

(3, 3)


In [68]:
rotation_matrix1

array([[ 0.99167675, -0.10235471,  0.07810739],
       [ 0.07656959,  0.95654786,  0.28134197],
       [-0.10351013, -0.27301964,  0.9564235 ]], dtype=float32)

In [69]:
jacob

array([[-3.9136509e-04,  3.6711410e-02,  5.3076841e-02,  5.3619348e-02,
         2.7737942e-01, -9.5766830e-01,  3.5914399e-02,  9.5805961e-01,
         2.7737358e-01],
       [-9.1414973e-02, -1.3674302e-01,  9.8144126e-01, -1.4228234e-01,
         6.6936703e-04,  3.6447525e-02, -9.8104990e-01,  5.3609964e-02,
        -9.0871908e-02],
       [-9.0059377e-02, -9.8113269e-01, -1.4228818e-01,  9.8152399e-01,
        -8.9526251e-02,  3.7254475e-02, -1.3674887e-01,  5.4162413e-02,
         6.6132797e-04]], dtype=float32)

In [70]:
jacob.shape

(3, 9)

In [71]:
tvec = np.array([[ 4.13072525],
                [ 0.9841125 ],
                [21.11944857]], dtype=np.float32)
print(tvec.shape)

(3, 1)


In [72]:
camera_pose = np.concatenate(
                (rotation_matrix1, tvec), axis=1
            )

In [73]:
print("camera pose using concat shape: {}\ncamera pose using concat matrix val: \n{}".format(camera_pose.shape, camera_pose))

camera pose using concat shape: (3, 4)
camera pose using concat matrix val: 
[[ 0.99167675 -0.10235471  0.07810739  4.1307254 ]
 [ 0.07656959  0.95654786  0.28134197  0.9841125 ]
 [-0.10351013 -0.27301964  0.9564235  21.119448  ]]


In [74]:
camera_pose1 = np.hstack((rotation_matrix1, tvec))

In [75]:
print("camera pose hstack shape: {}\ncamera_pose_hstack matrix val: \n{}".format(camera_pose1.shape, camera_pose1))

camera pose hstack shape: (3, 4)
camera_pose_hstack matrix val: 
[[ 0.99167675 -0.10235471  0.07810739  4.1307254 ]
 [ 0.07656959  0.95654786  0.28134197  0.9841125 ]
 [-0.10351013 -0.27301964  0.9564235  21.119448  ]]
